### ISSUE TITLE
Visual Studio solution is out of date.

### ISSUE THREAD

**Issue by NeilJed** [NeilJed/VTFLib#1]
The Visual Studio Solution in VTFLIb 1.3.2 is out of date for current editions of Visual Studio.

A new version needs to be created with the relevant settings.

**Comment by NeilJed** [comment]
Started adding VS2017 support as branch[ feature/vs2017-support](https://github.com/NeilJed/VTFLib/tree/feature/vs2017-support)

Currently prioritising VTFLib as some dependencies in VTFCmd and VTFEdit need more fixing.

**Comment by SupinePandora43** [comment]
why not 2019?

**Comment by NeilJed** [comment]
No reason other than 2017 is currently what I'm working with. Theres no reason 2019 can't be added as well, it's just project files mostly. Biggest issue is that the current code doesn't compile with current versions of Visual Studio and that needs to be fixed first. The priority is the VTFLib library as many projects have that as a dependency.

**Comment by Joshua-Ashton** [comment]
VS2019 removes old syntax support for CLR. I've ported it up to the latest version of the CLR and VS in my fork here: https://github.com/Joshua-Ashton/VTFLib/

I've also improved texture compression and SRGB handling for mipmaps, etc.

**Comment by NeilJed** [comment]
Thanks @Joshua-Ashton  - I'll try and take a look as soon as I have some free time.

**Comment by NeilJed** [comment]
@Joshua-Ashton are you planning on merging your fork back into the main repo?

**Comment by Joshua-Ashton** [comment]
I can clean stuff up at some point, I'm not sure if you would want all of the changes however.

**Comment by NeilJed** [comment]
Added a new Solution file for VS2022 for VTFLib for now including updating the C++ and C standards.
