### ISSUE TITLE
Can't find the precompiled VTFCmd.exe binary

### ISSUE THREAD

**Issue by BaptisteMartinet** [NeilJed/VTFLib#11]
Don't know if it's the right place to ask but is there anywhere i can grab the VTFCmd.exe binary file?
Thanks

**Comment by NeilJed** [comment]
Hmm... You're right. I always thought it was in the distribution. I confess, I didn't create the bundles, Ryan did and I just rescued them before his site disappeared. I'll try and build it and make a binary release bundle.

**Comment by TIMONz1535** [comment]
I found a github mirror with this archive
https://github.com/nemstools/nemstools.github.io/blob/master/files/vtflib132.zip

**Comment by TIMONz1535** [comment]
@NeilJed but there are still no VTFCmd binaries in the **Releases**. Can you just attach this archive to **VTFLib 1.3.2 release**?
